apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-sql
  labels:
    app: app-sql
spec:
  serviceName: app-sql-svc
  replicas: 2
  selector:
    matchLabels:
      app: app-sql
  template:
    metadata:
      labels:
        app: app-sql
    spec:
      containers:
        - name: sql
          image: shalomberman/api-sql:v1
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-sql
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: mysql-sql
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
